// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Supabase: DIRECT_URL (5432) untuk migrate, DATABASE_URL (6543 pooled) untuk app.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
